### PR TITLE
Mark `react-page` as unmaintained

### PR DESCRIPTION
**Pull request by petehunt**
We haven't done a great job of staying on top of issues for this project. I want to eventually revisit `react-page` as the _premier_ way to develop React components, but right now it's marketed as an easy way to create real-world apps or as an example of server rendering. There are easier, better maintained ways to create real-world apps and simpler examples of server rendering, so I think we should refocus this project as a development environment before encouraging people to use it again.

### CODE REVIEW

**Comment by jamesgpearce** [comment]
Consider moving to the /reactjs account in the meantime

**Comment by jordwalke** [comment]
This should be in the `reactjs` account. It was created before we had `github.com/reactjs`

**Comment by dazld** [comment]
which are the simpler ways of rendering on node? was thinking about a weekend project playing with async rendering, but came here and have sadface now to see this. is there something more up to date..?

**Comment by blissdev** [comment]
> There are easier, better maintained ways to create real-world apps and simpler examples of server rendering

@petehunt Could you please provide some links the references you mention?

**Comment by rtorr** [comment]
I would also be interested in what @blissdev mentioned :+1:

**Comment by xixixao** [comment]
@dazld @blissdev @rtorr https://github.com/mhart/react-server-example

**Comment by petehunt** [comment]
Also https://github.com/facebook/react/tree/master/examples/server-rendering was checked into the official repo yesterday.

**Pull request merged**
